### ISSUE TITLE
Create Self-Aware #support Tracking for Stats

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/podsbot#1]
As discussed, PodsBot already 'listens' to chat for it's particular things to track. All this would do would add to it's processes to:

- [ ] Track responses by 'speaker'
- [ ] Ignore Pods Staff
- [ ] Add DM to 'speaker' who says any of the keywords (help, hello), etc who hasn't received a response in say 15 minutes to advise by Direct Message the Support Policy hours, etc.
